# Generated by Django 4.1.5 on 2023-03-22 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_remove_fooditem_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
