# Generated by Django 4.1.5 on 2023-03-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_fooditem_created_at_fooditem_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="fooditem",
            name="updated_at",
        ),
    ]
